name: A new Bug appears !
description: "Report some bug/unexpected behaviours."
labels: [ "Bug" ]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        Please describe the issue with as much detail as possible.
        Explain what happened, and what should have happened instead.
        Add images, screenshots, or videos if they could be useful.
    validations:
      required: true
 - type: textarea
    attributes:
      label: Expected Behaviour
      description: >
        How do you think the feature should originally work
    validations:
      required: true


  - type: input
    attributes:
      label: Game Log
      description: >
        I need the game log for additional information about the bug.
        This file can be found in the \"logs\" folder of your Minecraft folder as \"latest.log\".
        Please upload the file to https://mclo.gs/ and put the link here.
        Do **not** paste the *contents* of the file here, because that will make this issue very hard to read.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Debug Information
      description: >
        Please run the \"/compressed debuginfos\" command in-game.
        This will copy useful information to your clipboard that will greatly help with debugging.
        Please paste this information here.
    validations:
      required: true
