name: My game crashed!
description: Report an issue that crashes the game.
labels: [ "Crash" ]
assignees: "iglee42"
body:
  - type: textarea
    attributes:
      label: Context
      description: What were you doing when the game crashed? Add images, screenshots, or videos if they could be useful.
    validations:
      required: true

  - type: input
    attributes:
      label: Crash Report
      description: >
        We need the crash report to figure out why the crash happened.
        This file can be found in the \"crash-reports\" folder of your Minecraft folder.
        It will be the newest file there.
        Please upload the file to https://mclo.gs/ and put the link here.
        Do **not** paste the *contents* of the file here, because that will make this issue very hard to read.
    validations:
      required: true
